version: '3.1'

services:

  mongodb:
    image: mongo
    ports:
       - 27017:27017
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: pass

  mysqldb:
      image: mysql:5.7
      ports:
        - 3306:3306
      environment:
        - MYSQL_ROOT_PASSWORD=parola
